---
run:
  go: "1.21"
  deadline: 2m
  build-tags:
    - mock
    - integration
    - e2e
linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - tagalign
    - varcheck
    - varnamelen
linters-settings:
  revive:
    rules:
      - name: unexported-return
        disabled: true
  misspell:
    locale: US
  gci:
    sections:
      - Standard
      - Default
      - Prefix(host.local)
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
          - host.local
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
